# Generated by Django 2.0 on 2018-01-01 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Asia'), ('a2', 'Animals'), ('b', 'Blacks'), ('c', 'Celebrity'), ('d', 'Dank'), ('f', 'Female'), ('g', 'Games'), ('h', 'Hitler'), ('i', 'Internet'), ('j', 'JoJoRef'), ('k', 'Kim Jong-un'), ('l', 'Lifehack'), ('m', 'Math'), ('n', 'Net Neutrality'), ('p', 'PC'), ('r', 'Religion'), ('r2', 'Russian'), ('s', 'Singer'), ('t', 'Taiwan'), ('u', 'USA'), ('v', 'Vehicle'), ('w', 'Welcom to HELL'), ('y', 'Yes/No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='userlikepost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Post'),
        ),
        migrations.AlterField(
            model_name='userlikepost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
