# Generated by Django 2.0 on 2018-01-01 10:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180101_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Asia'), ('a2', 'Animals'), ('b', 'Blacks'), ('c', 'Celebrity'), ('d', 'Dank'), ('f', 'Female'), ('g', 'Games'), ('h', 'Hitler'), ('i', 'Internet'), ('j', 'JoJoRef'), ('k', 'Kim Jong-un'), ('l', 'Lifehack'), ('m', 'Math'), ('n', 'Net Neutrality'), ('p', 'PC'), ('r', 'Religion'), ('r2', 'Russian'), ('s', 'Singer'), ('t', 'Taiwan'), ('u', 'USA'), ('v', 'Vehicle'), ('w', 'Welcom to HELL'), ('y', 'Yes/No')], max_length=47),
        ),
    ]
